### ISSUE TITLE
Clashes when pre-building different docker-compose configs with the same service name

### ISSUE THREAD

**Issue by toolmantim** [buildkite-plugins/docker-compose-buildkite-plugin#111]
If you have the same service name in two different docker-compose config files, and try to pre-build them for later steps, only the last completed step will be used.

For example, given the following pipeline both of the test commands will run against the prod image, instead of running against their respective images:

```yml
steps:
  - name: ":docker:"
    plugins:
      docker-compose#v1.8.4:
        build: app
        image-repository: org/app-dev

  - label: ":docker::zap:"
    plugins:
      docker-compose#v1.8.4:
        config: docker-compose.prod.yml
        build: app
        image-repository: org/app-prod

  - wait

  - label: ":hammer:"
    command: make test
    plugins:
      docker-compose#v1.8.4:
        run: app

  - label: ":hammer::zap:"
    command: make test
    plugins:
      docker-compose#v1.8.4:
        config: docker-compose.prod.yml
        run: app
```

Perhaps the meta-data key we use to the store the image name should be scoped to the the docker-compose config file as well, and not just the service name?
