### ISSUE TITLE
Version 1.8.3+ strange error related to docker-compose versions

### ISSUE THREAD

**Issue by shaneog** [buildkite-plugins/docker-compose-buildkite-plugin#113]
v1.8.3 and up of the plugin throw a strange error relating to Docker Compose versions.
There is no issue with v1.8.2 of this plugin.

Agent Version: v3.0-beta.39
Docker version: 17.12.1-ce
Docker Compose version: 1.19.0

Error Message:
```
/etc/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin-v1-8-4/hooks/../lib/shared.bash: line 70: ${#config_files[@]:-}: bad substitution
--
  | /etc/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin-v1-8-4/hooks/../lib/shared.bash: line 84: config[0]: unbound variable
  | The 'build' option can only be used with Compose file versions 2.0 and above.
  | For more information on Docker Compose configuration file versions, see:
  | https://docs.docker.com/compose/compose-file/compose-versioning/#versioning
```

pipeline.yml
```yaml
steps:
  - name: ":docker: Build"
    agents:
      queue: docker-builder
    plugins:
      docker-compose#v1.8.4:
        build: app
        config:
          - docker-compose.ci.yml
```

docker-compose.ci.yml
```yaml
version: '3.4'

services:
  app:
    build:
      context: .
```
