### ISSUE TITLE
Docker-compose service with image and build breaks run

### ISSUE THREAD

**Issue by lox** [buildkite-plugins/docker-compose-buildkite-plugin#12]
docker-compose recently introduced the ability to declare an `image` and a `build`:

https://docs.docker.com/compose/compose-file/#/image

> If the image does not exist, Compose attempts to pull it, unless you have also specified build, in which case it builds it using the specified options and tags it with the specified tag.

So for an example like this:

```
  accounts: 
    image: my-image/llamas:latest
    build:
      context: .
      dockerfile: ops/Dockerfile
    ports:
      - "9005:9005"
    depends_on:
      - mysql
```

This doesn't work with https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/hooks/commands/build.sh#L34.
