### ISSUE TITLE
Command appears to be mandatory

### ISSUE THREAD

**Issue by baank** [buildkite-plugins/docker-compose-buildkite-plugin#131]
If I have a pipeline.yml with the following:

```
steps:
  - name: ":docker: Build Image"
    plugins:
      docker-compose#v2.1.0:
        build: atlas
        image-name: ${DOCKER_TAG}
        image-repository: ${DOCKER_IMAGE_REPO}
```

Then it shows the following message:

> No command has been defined. Please go to "Project Settings" and configure your build step's "Command"
