### ISSUE TITLE
Why/When should I use docker-login? 

### ISSUE THREAD

**Issue by benschwarz** [buildkite-plugins/docker-compose-buildkite-plugin#146]
The readme says: 

> You can leverage the docker-login plugin in tandem for authenticating with a registry:

> ```
> steps:
>   - command: test.sh
>     plugins:
>       docker-login#v1.0.0:
>         username: myusername
>       docker-compose#v2.2.1:
>         build: app
> ```

I'm currently using `docker-compose` with `image-repository` on a 'run' command, is that the wrong way to do it? 

Eg: 

```
- name: ':rspec: requests'
    command: './script/spec requests'
    artifact_paths: ./rspec-screenshots/*.png
    env:
      RAILS_ENV: test
    plugins:
      docker-compose#v2.2.1:
        run: app
        image-repository: index.docker.io/benschwarz/app
```

Are there any negatives into what I've done above? It seems to work just fine? Or is this for if you want to use multiple repositories? (eg, docker hub and ECR).
