### ISSUE TITLE
Escaping environment variables with spaces?

### ISSUE THREAD

**Issue by rcoup** [buildkite-plugins/docker-compose-buildkite-plugin#164]
Trying to populate an environment variable for a test-runner
```
  - label: 'Action'
    plugins:
      docker-compose#v2.5.1:
        run: app
        environment:
          - "PROPERTIES=Buildkite: ${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER} ${BUILDKITE_BRANCH} ${BUILDKITE_COMMIT}"
```

But I end up with:
```
$ docker-compose ... run --name buildkite...e6c_mypipeline_build_123 -e PROPERTIES=Buildkite: mypipeline:123 mybranch abcdef12345abcdef12345 app

ERROR: No such service: mypipeline:123
```
(ie. the variable gets expanded on the command line without escaping it)

I've also tried:
```
- 'PROPERTIES="Buildkite: ${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER} ${BUILDKITE_BRANCH} ${BUILDKITE_COMMIT}"'
- "PROPERTIES='Buildkite: ${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER} ${BUILDKITE_BRANCH} ${BUILDKITE_COMMIT}'"
- 'PROPERTIES=Buildkite:\ ${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER}\ ${BUILDKITE_BRANCH}\ ${BUILDKITE_COMMIT}'
```
with the same results
