### ISSUE TITLE
Build is not able to actually build now?

### ISSUE THREAD

**Issue by piotrb** [buildkite-plugins/docker-compose-buildkite-plugin#18]
So I'm trying to use this plugin to set up a build then run chain .. and it seems like the recent changes that added the config override on build basically make that step entirely ineffective .. 

I don't really understand why it is the way it is .. but its looking like it overrides the config setting an image name .. making it impossible to ever actually build it .. 

![screen shot 2016-11-22 at 11 37 20 am](https://cloud.githubusercontent.com/assets/13251/20538913/0f52d276-b0a8-11e6-830f-db323e05fc49.png)

The related build step is:

```yaml
steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose:
        build: app
```
