### ISSUE TITLE
image-name containing latest and git hash

### ISSUE THREAD

**Issue by Eun** [buildkite-plugins/docker-compose-buildkite-plugin#180]
So I have the requirement to push the image onto a repository with multiple tags.
(the git hash and `latest`) how is this possible?

I tried this, but the documentation says multiple image-names are only for multiple builds.

```
steps:
  - label: ":building_construction: Build Container"
    plugins:
      docker-compose#v2.5.1:
        config: docker-compose.buildkite.yml
        build: docker-image-name
        image-name: 
            - ${BUILDKITE_COMMIT}
            - latest
        image-repository: registry/${BUILDKITE_BRANCH}

```
