### ISSUE TITLE
Running with arguments doesn't seem possible

### ISSUE THREAD

**Issue by viraptor** [buildkite-plugins/docker-compose-buildkite-plugin#197]
I've got a number of steps which use the same generic entry in `docker-compose.yml`. They're configured using an argument. This works just fine with `docker-compose` itself:
```
APP_PATH="Pipeline/Envato.Pipeline.Recurly.Tests" docker-compose run run_tests
```
This works with the following services description:
```
  run_tests:
    build:
      context: .
      dockerfile: Dockerfile.dotnet_test
      args:
        - APP_PATH
```

Unfortunately, it doesn't seem like the plugin can support it. It allows arguments in the `build` stage, but not `run`.

And if I do both build and run in a single step:
```
      - docker-compose#v2.6.0:
          build: run_tests
          args:
            - APP_PATH=....
      - docker-compose#v2.6.0:
          run: run_tests
```
I get a failure, because:
```
No pre-built image found from a previous 'build' step for this service and config file. Building image...
```
Even though it's just finished building one successfully.

Am I missing something? Or is this not possible / broken?
