### ISSUE TITLE
Running migration steps or multiple compose

### ISSUE THREAD

**Issue by pecigonzalo** [buildkite-plugins/docker-compose-buildkite-plugin#205]
Hi! we have some integration tests that require some database migrations, i wonder what is the recommended pattern for this (maybe outside this plugin scope).

I tried doing:
```
[...]
- label: ":hammer: Integration"
    plugins:
      - docker-compose#v2.1.0:
          run: migrator
          tty: false
          config:
            - docker-compose.yml
      - docker-compose#v2.1.0:
          run: integrator
          tty: false
          config:
            - docker-compose.yml
[...]
```
but since the images are cleaned up after the plugin runs, im left with no migrated DB.

We have a `depends'_on` in the compose file, but that is no guarantee the migration is actually finished.

I thought of using the integrator to query the DB or perform the migration, but to be honest, that seems rather awkward and not 1to1 on how the migration is run outside of Integration, not even close.

**Comment by toolmantim** [comment]
Hi there! It's a good question 🤔

Could you provide a minimal docker-compose.yml along with those pipeline.yml steps, so we can reproduce it locally and think about what a solution might look like?

**Comment by pecigonzalo** [comment]
Sure thing:
docker-compose.yml:
```
version: "2"

networks:
  app:
  db:

services:
  app:
    image: "nginx"
    depends_on:
      - migrator
      - db
    networks:
      - app
      - db

  migrator:
    image: "boxfuse/flyway:5-alpine"
    command:
      [
        "-url=jdbc:postgresql://db:5432/",
        "-user=postgres",
        "-password=mysecretpassword",
        "-connectRetries=60",
        "migrate",
      ]
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432
    networks:
      - db
```

docker-compose.it.yml:
```
version: "2"

services:
  integrator:
    image: "appropriate/curl"
    command: ["http://app/"]
    depends_on:
      - app
    networks:
      - app
```

migration/V1__create_users_table.sql:
```
create table users (
  id UUID primary key,
  name text not null,
  email varchar(100),
  dob date
);

```


We assume `app` connects to the DB and `integrator` performs a query that requires this app to connect to the DB.

Pipeline:
```
steps:
  - label: ":hammer: SBT Integration"
    plugins:
      - docker-compose#v2.1.0:
          run: migrator
          config:
            - docker-compose.yml
      - docker-compose#v2.1.0:
          run: integrator
          config:
            - docker-compose.yml
            - docker-compose.it.yml
```

Assuming the migration is fast enought we can avoid the first plugin declaration and rely in the `docker-compose.it.yml` `depends_on:`, but this is not true in many cases.
