### ISSUE TITLE
Plugin checkout failing

### ISSUE THREAD

**Issue by Cawllec** [buildkite-plugins/docker-compose-buildkite-plugin#223]
I seem to be getting an error where the plugin is unable to be checked out. This happens consistently on a single step on a single pipeline, but always works after restarting the step.

The error I see is:
```

$ git clone -v -- https://github.com/buildkite-plugins/docker-compose-buildkite-plugin .
--
  | Cloning into '.'...
  | POST git-upload-pack (gzip 2515 to 1313 bytes)
  | remote: Enumerating objects: 70, done.
  | remote: Counting objects: 100% (70/70), done.
  | remote: Compressing objects: 100% (39/39), done.
  | remote: Total 2506 (delta 34), reused 52 (delta 27), pack-reused 2436
  | Receiving objects: 100% (2506/2506), 634.95 KiB \| 7.38 MiB/s, done.
  | Resolving deltas: 100% (1339/1339), done.
  | # Checking out `2.6.0`
  | $ git checkout -f 2.6.0
  | error: pathspec '2.6.0' did not match any file(s) known to git.
  | $ cd /
  | $ cd /var/lib/buildkite-agent/builds/buildkite-i-01b25465a899d018f-5/bugsnag/android-bugsnag-notifier
  | 🚨 Error: Failed to checkout plugin docker-compose: Error running `/usr/bin/git checkout -f 2.6.0`: exit status 1
  |  


```

And the step is:
```
  - label: ':android: NDK Instrumentation tests'
    plugins:
      - docker-compose#2.6.0:
          run: android-instrumentation-tests
```

Do you have any suggestions as to why this might be?
