### ISSUE TITLE
Docker caching not working

### ISSUE THREAD

**Issue by lox** [buildkite-plugins/docker-compose-buildkite-plugin#23]
It appears that docker caching isn't working. To reproduce, scale down your builder stack to 1 host, and then run a docker build step a few times. Steps aren't cached.

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/hooks/commands/build.sh#L22

**Comment by toolmantim** [comment]
Closed by #24

**Comment by badosu** [comment]
Is caching enabled only if `cache-from` is specified?

All our builds do not reuse any cached step.

This is my config:

```yaml
steps:
  - plugins:
      docker-compose#v2.5.1:
        run: ci
```
