### ISSUE TITLE
skip-checkout doesn't seem work as expected

### ISSUE THREAD

**Issue by akum32** [buildkite-plugins/docker-compose-buildkite-plugin#232]
When using `skip-checkout` in a run step, I receive the error `docker-compose.yml` not found (in `lib/shared.bash: line 118`) when the plugin is `Creating docker-compose override file for prebuilt services`.

I guess this is understandable given my `docker-compose.yml` is checked into the repo...but then I'm confused how this is even supposed to work in the first place?

```
steps:
  - label: Bootstrap
    plugins:
      - docker-compose#v3.0.3:
          build: app
          image-repository: <my-repo>
    
  - wait

  - command: <some-command>
    plugins:
       - docker-compose#v3.0.3:
          run: app
          skip-checkout: true
```
