### ISSUE TITLE
Pre building docker image not working

### ISSUE THREAD

**Issue by Matthijsy** [buildkite-plugins/docker-compose-buildkite-plugin#239]
Hi all,

I have a problem with pre building a docker image such that it does not have to build at the moment I run my tests (in parallel). I have a buildkite pipeline as below. I would expect that the build test image step will build the image, and that both tests won't need to rebuild this image since it is already build. However, at the start of both tests it logs `⚠️ No pre-built image found from a previous 'build' step for this service and config file. Building image...` and starts rebuilding the image (from the cache so it is quite fast but still takes some time). This is not the expected behavior right? Or is this something I do wrong?

```
  - label: ":docker: Build test image"
    plugins:
      - docker-compose#v2.6.0:
          build: app
          config: docker-compose.buildkite.yml

  - wait

  - label: "test a"
    command: ["test_commando"]
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

  - label: "test b"
    command: ["test_commando_b"']
    plugins:
      - docker-compose#v2.6.0:
          run: app
          config: docker-compose.buildkite.yml

```
