### ISSUE TITLE
Simplifying Plugin Configurration

### ISSUE THREAD

**Issue by elijahchancey** [buildkite-plugins/docker-compose-buildkite-plugin#240]
Here's my current docker compose plugin configuration:
```
  - name: "Build"
    plugins:
      docker-compose#v3.1.0:
        build: "myapp"
        cache-from: myapp:111111111111.dkr.ecr.us-west-1.amazonaws.com/myapp:latest
        config:
          - docker-compose-buildkite.yml
        image-repository: 111111111111.dkr.ecr.us-west-1.amazonaws.com/myapp
        image-name: latest
        push:
          - myapp:111111111111.dkr.ecr.us-west-1.amazonaws.com/myapp:bk-$BUILDKITE_BUILD_NUMBER
```

I think it would've been easier to figure out if the plugin would have supported something like this:
```
  - name: "Build"
    plugins:
      docker-compose#v3.1.0:
        build: "myapp"
        cache-from-tag: 'latest'
        config:
          - docker-compose-buildkite.yml
        image-repository: 111111111111.dkr.ecr.us-west-1.amazonaws.com/myapp
        image-name: ['latest', 'bk-$BUILDKITE_BUILD_NUMBER']
```

There may be gotchas I'm not aware of...but it did take a bit too long for me to figure out my current (and working) configuration. Thanks!
