### ISSUE TITLE
Specify image name/tag when pre-building and running

### ISSUE THREAD

**Issue by evandam** [buildkite-plugins/docker-compose-buildkite-plugin#245]
Sorry if this is covered somewhere, but having trouble finding an answer in the docs.

I am trying to pre-build an image and run some tests in parallel. I would like to specify how the tags are created to be something like `buildkite-${GIT_BRANCH}-${BUILDKITE_BUILD_NUMBER}`.

I'm able to get the build step to tag and push correctly, but the run steps do not pull the image. I've tried adding `image-name` and `pull` attributes to the run steps, but neither seem to be the right ones.

Here's what I have so far. How can I modify the run step to pull the correct tag?

```yaml
steps:
  - label: ":docker: build"
    key: build
    plugins:
      - docker-compose#v3.1.0:
          build: web
          image-name: "quay.io/myorg/myrepo:buildkite-$${BUILDKITE_BRANCH}-$${BUILDKITE_BUILD_NUMBER}"
          cache-from: "web:quay.io/myorg/myrepo:buildkite-latest"
          config: docker-compose-ci.yml

  - label: ":docker: test %n"
    key: test
    commands:
      - echo "test me"
    parallelism: 3
    plugins:
      - docker-compose#v3.1.0:
          run: web
          pull: "quay.io/myorg/myrepo:buildkite-$${BUILDKITE_BRANCH}-$${BUILDKITE_BUILD_NUMBER}"
          config: docker-compose-ci.yml
    depends_on:
      - build
```

**Comment by scalp42** [comment]
having the same issue, @lox do you have any insight maybe?

**Comment by KaanOzkan** [comment]
+1. Default naming scheme isn't informative enough. I'd love to see a fix for this. Is it possible to put this on the roadmap? @lox

**Comment by jayco** [comment]
Hey @evandam it is a little confusing but you don't need to specify the pull in next step because the pipeline is actually creating a docker-compose-override.yml here with the details about the app which it uses to push and pull (implicitly when running).  You can check this out in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/commands/run.sh

**Comment by evandam** [comment]
Sorry for the delay getting back to you on this, I detoured in another direction for a while.

I think I found the right combination of params to accomplish what I'm looking for. It's a little misleading but it seems like `image-name` is for specifying the tag to use? Either way, I'll close this out.

```yaml
steps:
  - label: Build image
    key: build
    plugins:
      - $COMPOSE_PLUGIN:
          config: $COMPOSE_FILE
          build: web-test
          image-repository: $DOCKER_REPO
          image-name: ${BUILDKITE_BRANCH}-latest
```
