### ISSUE TITLE
Pushing pre-built images can take a long time

### ISSUE THREAD

**Issue by huonw** [buildkite-plugins/docker-compose-buildkite-plugin#246]
We distribute our software as docker images, so, on CI, we use this plugin to very conveniently:

1. prebuild the images (and push them to docker hub under the default plugin's tag names)
2. run tests inside them
3. push those exact images under "published" tag names, e.g.:
   - for a release, we publish `latest` and `x.y.z` tags,
   - for our `develop` branch (following git-flow), we push prerelease `SNAPSHOT` tags for manual testing and bleeding-edge users
   - for each PR, we push `PR-...` tags for manual testing

For our products, we've got 4 independent images that we push, and some of them images are unfortunately ~a gigabyte large, due to the stack we're building on (the Spark/hadoop ecosystem). This means the time to download the large image(s) is significant, and the final publish step takes almost 4 minutes:

![image](https://user-images.githubusercontent.com/1203825/69285295-a1cb8300-0c44-11ea-8cdb-da948eea9f0a.png)

For our devops support images, we've got 8 independent images to push, all relatively small. Each of these downloads and uploads quickly, but the number and the latency of doing all of this in serial means the final publish step takes 2.5 minutes:

```yaml
...

  - label: ":docker: push images"
    plugins:
      docker-compose#v3.1.0:
        push:
          - dashboard:index.docker.io/stellargraph/stellar-dashboard:${IMAGE_TAG}
          - kubectl:index.docker.io/stellargraph/kubectl:${IMAGE_TAG}
          - cfn-lint:index.docker.io/stellargraph/cfn-lint:${IMAGE_TAG}
          - jobs:index.docker.io/stellargraph/kubernetes-job-scheduler:${IMAGE_TAG}
          - black:index.docker.io/stellargraph/black:${IMAGE_TAG}
          - dockerfile-utils:index.docker.io/stellargraph/dockerfile-utils:${IMAGE_TAG}
          - hadolint:index.docker.io/stellargraph/hadolint:${IMAGE_TAG}
          - yamllint:index.docker.io/stellargraph/yamllint:${IMAGE_TAG}
```

![image](https://user-images.githubusercontent.com/1203825/69285256-83fe1e00-0c44-11ea-9da4-0b41092b683f.png)

It would be nice if this time could be optimised. Some possibilities might be:

- if pulling/pushing to docker hub (or other known registries) use the API to retag the image directly (e.g. https://github.com/joshdk/docker-retag) rather than having to do a round-trip to the agent
- do more work in parallel, since, at least once the images are pulled, re-pushing a single one is unlikely to be saturate the network (since nothing actually gets uploaded) (I think this can be emulated by splitting the full `push` array across multiple steps)
