### ISSUE TITLE
cant find logs on run

### ISSUE THREAD

**Issue by shavo007** [buildkite-plugins/docker-compose-buildkite-plugin#247]
I have an issue on buildkite running tests with docker compose plugin.

I need to view the logs for all containers to see whats going on

```
  - label: ':jest: Run Local E2E'
    timeout_in_minutes: 15
    agents:
      queue: 'agent:cicd'
    plugins:
      <<: *npm-login
      docker-compose#v3.1.0:
        run: e2e
        upload-container-logs: always
```

I do not see any logs uploaded as artifacts. Is there something else i need to do?

Thanks,
Shane
