### ISSUE TITLE
Getting a `Failed to run command exited with 245` and `The command exited with status 139`

### ISSUE THREAD

**Issue by gregtandiono** [buildkite-plugins/docker-compose-buildkite-plugin#253]
Hi,
I'm getting a `Failed to run command exited with 245` and `The command exited with status 139` See last few lines below:

```
docker-compose -f docker-compose.test.yml -p buildkitef572cd55da0d4f6f8522f2aac7676786 run --name buildkitef572cd55da0d4f6f8522f2aac7676786_integration-test_build_546 integration-test npm test
--
  | Starting buildkitef572cd55da0d4f6f8522f2aac7676786_mongo_1 ... done
  | Starting buildkitef572cd55da0d4f6f8522f2aac7676786_redis_1 ... done
  | ⚠️ Failed to run command, exited with 245 | 0s
  | # ↳ Command completed in 3.955509332s
  | 🚨 Error: The command exited with status 139
```

My pipeline file:

```yaml
steps:
  - label: ":docker: run"
    plugins:
      - docker-compose#v3.1.0:
          run: integration-test
          config: docker-compose.test.yml
          command: ["npm", "test"]
```

Docker compose file:

```yaml
version: "3.7"
services:
  integration-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - mongo
      - redis
    networks:
      - webnet
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet

networks:
  webnet:
```

I've tried variations of the `command` property of the `pipeline` file, and I get the same results. Any help is appreciated!
