### ISSUE TITLE
Support for Buildkit?

### ISSUE THREAD

**Issue by evandam** [buildkite-plugins/docker-compose-buildkite-plugin#256]
Hey @lox, I've been looking around and I know there's no official support for buildkit baked into docker-compose as of now, but I found stumbled across https://github.com/lox/docker-compose-buildkit 😄

Are there any plans to use your shim for `docker-compose` in this plugin? It would be really useful! 

The most important feature I'm looking for is around `docker build --ssh`, since builds may reference private GitHub repos for dependencies.

In the meantime, would a decent approach be to have a step to manually pre-build an image with a `docker build && docker push` and have a `docker-compose.yml` that references that image directly for this plugin to use?

**Comment by vgrigoruk** [comment]
it looks like `docker-compose build` supports Buikdkit (https://github.com/moby/buildkit/issues/685#issuecomment-550993592). However, it doesn't seem like setting those 2 env vars (`DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1`) enable Buildkit for docker-compose invoked from this plugin. Any ideas why?

**Comment by arturopie** [comment]
I got it to work by setting those env variables 
```
    env:
       DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    plugins:
      docker-compose#v3.3.0:
        ...
```

Keep in mind that you need docker-compose 1.25.1+
The problem now is how to change the output so it uses plain on buildkite (the buildkit generates a lot of output by default)

**Comment by tjwallace** [comment]
@arturopie you can add `BUILDKIT_PROGRESS: plain` to `env`

**Comment by arturopie** [comment]
> @arturopie you can add `BUILDKIT_PROGRESS: plain` to `env`

TIL. It works. Thanks!

**Comment by mubeta06** [comment]
Is there any way to support `ssh` mounts? I've attempted setting both `DOCKER_BUILDKIT: 1` and 
`COMPOSE_DOCKER_CLI_BUILD: 1` along with some `args` with no luck yet 🤔.

**Comment by vgrigoruk** [comment]
AFAIK there is no support for passing additional to `docker build` from docker-compose CLI  at the moment, @mubeta06 
Check these tickets for more context:
- https://github.com/docker/compose/pull/7296
- https://github.com/docker/compose/issues/7025

**Comment by EnricoMi** [comment]
I cannot get the docker-compose plugin work with Buildkit. This is my Buildkite pipeline:

```
steps:
- label: ':docker: Build test-cpu-...'
  env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1
    BUILDKIT_PROGRESS: plain
  plugins:
  - docker-compose#v3.5.0:
      build: test-cpu-...
      config: docker-compose.test.yml
      ...
```

I get: `ERROR: Dockerfile parse error line 33: Unknown flag: mount`, which I presume is because it runs the classic build and not buildx / buildkit. Looks like the plugin does not provide the given envs to the docker-compose command. I have even added a repository hook to set those env vars.

My `docker-compose.test.yml` works perfectly fine locally with this command:

```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.test.yml build test-cpu-...
```

Do you have any hints of what might possibly go wrong here or how to debug what Buildkite is doing with my envs?

**Comment by EnricoMi** [comment]
I have found the issue, though I have the right docker-compose version, my docker version is 18.06, where at least 18.09 is needed.

**Comment by henare** [comment]
Another thing that just tripped us up is that when using Buildkit it wasn't using the cached layers from the [`image-repository`](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#image-repository-optional-build-only) we were fetching with [`cache-from`](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#cache-from-optional-build-only). After much fiddling we discovered that [Buildkit doesn't include the cache metadata with the image](https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources) by default. So even though it fetches the image it can't use the layers from that image for the build cache.

To include the cache metadata set the [build arg](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#args-optional-build-and-run-only) `BUILDKIT_INLINE_CACHE=1`. After setting that, the image that gets pushed to the `image-repository` will include the cache metadata and subsequent builds that `cache-from` it will be able to take advantage of the build cache.

So now the example above would look like...

```yaml
steps:
- label: ':docker: Build test-cpu-...'
  env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1
    BUILDKIT_PROGRESS: plain
  plugins:
    - docker-compose#v3.5.0:
        build: test-cpu-...
        config: docker-compose.test.yml
        args:
          - BUILDKIT_INLINE_CACHE=1
      ...
```

Which means to enable Buildkit you need to remember to put 4 different things in your pipeline configuration. It would be great to, "_...[just add](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/281#issuecomment-658593161) a `buildkit: true` option to the plugin, which sets [everything for you]._' :grinning: 

@toolmantim what are the, "[_parts of the output that we'll need to modify if `buildkit` is set to true_](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/281#issuecomment-664122361)"? Asking to understand what else would be involved in adding support for this magic Buildkit option.
