### ISSUE TITLE
Branch names with "/" fail when used in Docker tags

### ISSUE THREAD

**Issue by toolmantim** [buildkite-plugins/docker-compose-buildkite-plugin#265]
A common workflow of using `cache-from` is to include the branch name, via `${BUILDKITE_BRANCH}`, in the Docker tag. But if someone pushes a branch with a `/` character in it (e.g. Dependabot's default behaviour), it will create an invalid tag and the push will fail.

For example:

```yml
steps:
  - plugins:
      - docker-compose#3.2.0:
          build: app
          cache-from:
            - app:index.docker.io/my-org/my-repo:${BUILDKITE_BRANCH}
            - app:index.docker.io/my-org/my-repo:master
          push:
            - app:index.docker.io/my-org/my-repo:${BUILDKITE_BRANCH}
```
