### ISSUE TITLE
Running multiple containers

### ISSUE THREAD

**Issue by doron-cohen** [buildkite-plugins/docker-compose-buildkite-plugin#269]
Hi,

I would like to know if it is possible to run multiple containers in one step. My scenario is an API integration test and it requires a DB to run along. Is there a way to leverage this plugin for this? Or should I do it manually?

Thanks

**Comment by scream314** [comment]
@doron-cohen 
Do you want to run different commands in multiple containers (eg. using multiple `command` and `run` params here:
```
  - label: '*********'
    command: '*********'
    plugins:
      docker-compose#vX.X.X:
        run: app
        config: 'docker-compose.yml'
```
), or just have multiple containers running?

If the second one is your case, you can start as many containers you want in your Composefile (the same way as you use it locally w/ `docker-compose up`).

If your requirement is the first... I doubt it would be easy if doable at all.
Maybe you could try to build in/mount your scripts in the containers and use `docker-compose`'s `entrypoint:` param to override the default entrypoint and run your script/command instead.

I hope this helps...

**Comment by doron-cohen** [comment]
Hey @scream314 . I want to run a PostgreSQL container in the background and then run integration tests against it.
If I understand correctly, you are saying that I can have this `docker-compose.yaml`:
```yaml
version: '3.1'

services:
  db:
    image: postgres:12
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ********
  app:
    image: *****
    ports: 
      - 8080:8080
```
So running this:
```yaml
  - label: Integration Tests
    command: ./pytest integration
    plugins:
      docker-compose#vX.X.X:
        run: app
        config: 'docker-compose.yml'
```
Will run the pytest command using the `app` service while the `db` service runs in the back ground?
