### ISSUE TITLE
How to pass the agent's SSH authentication socket?

### ISSUE THREAD

**Issue by scream314** [buildkite-plugins/docker-compose-buildkite-plugin#274]
I have a step using the `docker-compose-buildkite-plugin`, where I need to make operations on a private Git repository.
My idea was to pass the agent's `SSH_AUTH_SOCK` to the container (as the agent has access to the repo). As there is no `mount-ssh-agent` option in this plugin, I took a look at what that option does in the `docker-buildkite-plugin`, and tried to manually reproduce the behaviour on my compose stack by setting
```
...
 docker-compose#v3.0.0:
...
   environment:
     - SSH_AUTH_SOCK=/ssh-agent.sock
   volumes:
     - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts:ro
     - ${SSH_AUTH_SOCK}:/ssh-agent.sock
...
```
My problem is, that while `${SSH_AUTH_SOCK}` exists and is a socket on the agent, the mounted volume `/ssh-agent.sock` is a directory inside the container for some reason, and I cannot figure out why (note: this is on Linux, not on macOS).

Why is this happening?
Is there an easy way to pass the SSH authentication socket?

**Comment by jufemaiz** [comment]
For the record, the best practice AFAIK is currently:

```yaml
...
  docker-compose#v3.0.0:
...
    environment:
    - SSH_AUTH_SOCK=/ssh-agent
    volumes:
    - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    - /run/host-services/ssh-auth.sock:/ssh-agent
...
```
