### ISSUE TITLE
docker-compose plugin complaining about version mismatches

### ISSUE THREAD

**Issue by PHILLIPS71** [buildkite-plugins/docker-compose-buildkite-plugin#289]
I've been playing around with now for a few hours and cannot figure what is going wrong. I've tried multiple different versions, but I continue to get the same error message. As soon as Buildkite attempts to build the image with docker compose it runs into this. Unsure if I've configured this or doing something wrong if so please correct me as I've been trying to figure this out for far too long.

pipleline.yml
```yml
steps:
  # Build the image in a single place for all parallel steps to leverage the same image.
  - label: ':docker: :package:'
    plugins:
      - docker-compose#v3.7.0:
          build: testing
          env: DOCKER_BUILDKIT=1
  # Wait until all images are built.
  # This way we can download the built image from a registry instead of building each for each test task.
  - wait
  # All of the commands after the wait are run in parallel.
  - label: ':typescript:'
    command: yarn tsc
    plugins:
      - docker-compose#v3.7.0:
         run: testing

  - label: ':eslint:'
    command: yarn lint
    plugins:
      - docker-compose#v3.7.0:
          run: testing
```

docker-compose.yml
```yml
version: '2.3'
services:
  testing:
    build: .
    environment:
      - BUILDKITE
      - BUILDKITE_API_TOKEN
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_PULL_REQUEST_REPO
      - BUILDKITE_COMMIT
      - BUILDKITE_MESSAGE
      - GITHUB_AUTH_TOKEN
```

```
$ docker-compose -f docker-compose.yml -p buildkite348ef14dfe6442fe9bf1e0f825fdfe93 -f docker-compose.buildkite-89-override.yml build --pull testing
--
  | ERROR: Version mismatch: file ./docker-compose.yml specifies version 2.3 but extension file ./docker-compose.buildkite-89-override.yml uses version 2.3
  | 🚨 Error: The command exited with status 1
```
