### ISSUE TITLE
`$$my_env` works `%24my_env` like showing in url

### ISSUE THREAD

**Issue by myeonghan-nim** [buildkite-plugins/docker-compose-buildkite-plugin#296]
I use docker-compose plugin for build my github project like below.

```yaml
steps:
  - label: "TEST"
    plugins:
      - docker-login#v2.0.1:
          username: $ID
          password-env: PASSWORD
      - docker-compose#v3.7.0:
          run: my_app
          args:
            - MY_AWS_ID=$$MY_AWS_ID
            - MY_AWS_PASSWORD=$$MY_AWS_PASSWORD
```

In buildkite official document, `$$MY_AWS_ID` and `\$MY_AWS_ID` work as same as `$MY_AWS_ID`, but in docker-compose plugin, it works like `%24MY_AWS_ID`. Do you have any plans to correct this difference?
