### ISSUE TITLE
docker-compose run with env_file

### ISSUE THREAD

**Issue by jack1902** [buildkite-plugins/docker-compose-buildkite-plugin#297]
## How to fix

Below is the original issue if you are interested in reading it but to fix this for anyone who comes across this in the future or future me 👋 

Set `shell: ["/bin/bash", "-e", "-c"]` since `/bin/sh` doesn't appear to contain the variables set by `env_file`

```yml
steps:
  - label: ":docker: simple example"
    command: "echo i am a normal command"
    plugins:
      - docker-compose#v3.7.0:
          # This is needed because sh didn't contain my variables
          shell: ["/bin/bash", "-e", "-c"]
          run: dev
          mount-buildkite-agent: true
```

## Background (Original issue)

TL;DR Running a service with `env_file` doesn't have the env variables set in CI

I am running a compose file which has two services defined `app` and `db`. The `app` depends on the `db` which is a prebuilt image. This works great locally as any env-variable i need in `app` is container within a `.env.development` file locally.

In `docker-compose` i have `env_file` defined like the below:

```yml
version: "3"
networks:
  main:

services:
  dev:
    build:
      context: .
      target: dev
    env_file:
      - .env.development
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
    networks:
      - main
    working_dir: /app
  db:
    image: postgres:12.5
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: password
    ports:
      - "5400:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - main

volumes:
  db:
```

When i run the `dev` service in Buildkite to run some tests i have, i expected that the `env_file` would have been detected (it works fine locally) but for some reason it just doesn't want to work in Buildkite.

Additionally, when i am running in CI, i have a `pre-command` hook defined to do:

```bash
cp .env.example .env.development
```
This ensures that i am not just using the `example` env file as the source of truth in local dev and prevents acidental commits of secrets to git
