### ISSUE TITLE
Entrypoint property not valid?

### ISSUE THREAD

**Issue by evandam** [buildkite-plugins/docker-compose-buildkite-plugin#299]
Hi folks,

I'm trying to set the entrypoint on a step and it doesn't seem to be a valid option?

```
🚨 Error: /entrypoint: "" cannot match schema
```

My pipeline:

```yaml
steps:
- label: Lint
  key: lint
  command: lint
  plugins:
    - docker-compose#v3.7.0:
        run: web
        entrypoint: "npm run"
```

Looking through https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/plugin.yml it seems it was never added? Not sure if I'm missing something.

cc @emilio-notable

**Comment by emilio-notable** [comment]
does buildkite validate the schema automatically using the plugin.yml?
if that's the case, i think you are right, it is missing that option.

What's weird to me is that we are using the `entrypoint` option right now, and it is not causing the schema error.
We are using `docker-compose#v3.6.0`, and using `buildkite-agent pipeline upload` to define the pipeline. Maybe the `pipeline upload` command doesn't validate the schema?

**Comment by evandam** [comment]
Do you have an example pipeline that works? I have a feeling there's something weird with the combination of entrypoint and how the command is passed but I'm not sure. I'm trying something like this maybe, also dropped down to v3.6.0, also using `buildkite-agent pipeline upload`:

```yaml
steps:
- label: Lint
  key: lint
  plugins:
    - docker-compose#v3.6.0:
        run: web-dev
        command: ["lint"]
        entrypoint: "npm run"
```

**Comment by emilio-notable** [comment]
we hace something like this:

```yaml
steps:
  - label: 'test'
    depends_on: 'another_step'
    timeout_in_minutes: 20
    parallelism: 3
    plugins:
      docker-compose#v3.6.0:
        run: web
        entrypoint: sh -c 'npm run test'
        pull:
          - web
        config:
          - docker-compose.yml

```
