### ISSUE TITLE
[Issue] `soft_fail` doest work with `docker-compose plugin`

### ISSUE THREAD

**Issue by krivi95** [buildkite-plugins/docker-compose-buildkite-plugin#304]
Hi,

I'm having an issue with the latest version of plugin:`docker-compose#v3.7.0` when using combined with `soft_fail` feature ([buildkite docs](https://buildkite.com/changelog/56-command-steps-can-now-be-made-to-soft-fail)). Using soft_fail worked perfectly before switching to docker_compose plugin.

I'm using a `pre-building step` to build a docker image and to push it to private `AWS ECR` (`docker-compose` + `ecr` plugins). And in the other pipeline steps, that image is just pulled from ECR.

For an example we don't want test coverage to break the whole building process, but just to give us a warning, so we want to used `soft_fail` for that option.

Here is pipeline example for described scenario:
```yaml
steps:
  - label: ":docker: Build"
    plugins:
      - ecr#v2.3.0:
          login: true
          account_ids: "1111111111111"
          no-include-email: true
          region: us-east-1 
      - docker-compose#v3.7.0:
          build: app
          config: docker-compose.buildkite.yml
          image-repository: 1111111111111.dkr.ecr.us-east-1.amazonaws.com/test
          cache-from: app:1111111111111.dkr.ecr.us-east-1.amazonaws.com/test:latest
          push:
            - app:1111111111111.dkr.ecr.us-east-1.amazonaws.com/test
            - app:1111111111111.dkr.ecr.us-east-1.amazonaws.com/test:latest
    agents:
      queue: "elastic"

  - wait

- label: "Test Coverage"
    command: make test-coverage
    plugins:
      - ecr#v2.3.0:
          login: true
          account_ids: "1111111111111"
          no-include-email: true
          region: us-east-1 
      - docker-compose#v3.7.0:
          run: app
          config: docker-compose.buildkite.yml
    soft_fail:
      - exit_status: 2
    agents:
      queue: "elastic"
```

And the error message:
```
make: *** [Makefile:119: test-coverage] Error 1
ERROR: 2
^^^ +++

+++ ⚠️ Failed to run command, exited with 2, run params:
🚨 Error: The command exited with status 2
^^^ +++
^^^ +++
user command error: The plugin docker-compose command hook exited with status 2

...

>>> 🚨 Command failed in 48.278037833s
🚨 Job failed with code 2
make: *** [buildkite] Error 1
```

I've tried also moving the `soft_fail` on the plugin level, but it doesn't work:
```yaml
- docker-compose#v3.7.0:
          run: trialhq
          config: docker-compose.buildkite.yml
          soft_fail:
            - exit_status: 2
```

I've also tried with `allow_dependency_failure `, `allow_failure` flags, but unfortunately it doesn't change the outcome.

Did anybody maybe encounter similar problem or know maybe where the issue might be?

Thanks!
