### ISSUE TITLE
`build` is invalid: configuration must be defined with a hash

### ISSUE THREAD

**Issue by juliosaraiva** [buildkite-plugins/docker-compose-buildkite-plugin#305]
This is my pipeline.yml file
```
steps:
  - plugins:
      - "docker-compose#v3.7.0":
        build: tavola
        config:
          - docker-compose.buildkite.yml
    branches: "buildkite"
  - wait:
  - command: bundle exec rake spec
    plugins:
      - "docker-compose#3.7.0":
        run: tavola
```

This is what's happening when pipeline run.
```
2021-06-13 09:38:07 WARN   POST https://agent.buildkite.com/v3/jobs/f2b663d9-ee78-4512-8c78-f86bc4bfb40b/pipelines: 422 `build` is invalid: configuration must be defined with a hash (Attempt 1/60 Retrying in 5s)
--
&nbsp; | 2021-06-13 09:38:07 ERROR  Unrecoverable error, skipping retries
&nbsp; | 2021-06-13 09:38:07 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/f2b663d9-ee78-4512-8c78-f86bc4bfb40b/pipelines: 422 `build` is invalid: configuration must be defined with a hash
&nbsp; | 🚨 Error: The command exited with status 1
&nbsp; | user command error: exit status 1
```

How can I fix that?
