### ISSUE TITLE
Environment variables defined by buildkite should be automatically injected into containers

### ISSUE THREAD

**Issue by BRMatt** [buildkite-plugins/docker-compose-buildkite-plugin#34]
I'm new to docker and buildkite's docker compose plugin so I was a bit confused as to why the environment variables that were showing up in the "Environment" tabs in my builds weren't available within the containers. Eventually I realised I need to explicitly whitelist them in the `docker-compose.yml` config, e.g.

```yml
services:
  my_container:
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_PROJECT_SLUG
      - ANOTHER_VAR_I_DEFINED_IN_PIPELINE.YML
```

It'd be nice if these variables were injected by default, so that the experience lines up with what the UI is suggesting will happen.
