### ISSUE TITLE
Plugin doesn't pull the latest image during `run`

### ISSUE THREAD

**Issue by alpozcan** [buildkite-plugins/docker-compose-buildkite-plugin#351]
We have a deployment helper toolkit called `deploy-tools` that comes as a container image which performs the actual deployment.

Snippet from our docker-compose.yml:
```
  deploy-tools-development:
    image: REDACTED.dkr.ecr.us-east-1.amazonaws.com/deploy-tools:latest
    pull_policy: always
    volumes:
      - .:/code-to-deploy
```

And the relevant snippet from our .buildkite/pipeline.yml:
```
  - label: "development deployment"
    command: deploy-terraform --code-dir /code-to-deploy/credentials/development
    branches: "master"
    agents:
      stage: "development"
    plugins:
      - ecr#v2.5.0:
          login: true
          assume_role:
            role_arn: arn:aws:iam::REDACTED:role/eks-cluster-deployer
      - docker-compose#v4.3.0:
          run: deploy-tools-development
          skip_pull: false
          no-cache: true
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
      - cultureamp/aws-assume-role#v0.1.0:
          role: arn:aws:iam::REDACTED:role/eks-cluster-deployer
```

Already tried:

- Set `skip_pull: false` and `no-cache: true` in .buildkite/pipeline.yml
- Set `pull_policy: always` in docker-compose.yml

But no matter what, the image used in that service `deploy-tools-development` is an old version and not the `latest`:

Snippet from BuildKite log:
```
...
Running plugin docker-compose pre-checkout hook | 0s
-- | --
  | Preparing working directory | 1s
  | Running global pre-command hook | 0s
  | Running plugin aws-assume-role pre-command hook | 0s
  | Assuming IAM role arniam::REDACTED:role/eks-cluster-deployer ... | 1s
  | Running plugin docker-compose command hook | 0s
  | $ /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin-v4-3-0/hooks/command
  | Building Docker Compose Service: deploy-tools-development | 1s
  | ⚠️ No pre-built image found from a previous 'build' step for this service and config file. Building image...
  | $ docker-compose -f docker-compose.yml -p buildkite0183e93ce0fd4568be873e083e43031d build --pull --no-cache deploy-tools-development
  | deploy-tools-development uses an image, skipping
  |  
  | Starting dependencies | 1s
  | $ docker-compose -f docker-compose.yml -p buildkite0183e93ce0fd4568be873e083e43031d up -d --scale deploy-tools-development=0 deploy-tools-development
  | Creating network "buildkite0183e93ce0fd4568be873e083e43031d_default" with the default driver
  |  
  | Running /bin/sh -e -c 'deploy-terraform --code-dir /code-to-deploy/credentials/development' in service deploy-tools-development | 12s
  | $ docker-compose -f docker-compose.yml -p buildkite0183e93ce0fd4568be873e083e43031d run --name buildkite0183e93ce0fd4568be873e083e43031d_deploy-tools-development_build_1750 -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN --rm deploy-tools-development /bin/sh -e -c 'deploy-terraform --code-dir /code-to-deploy/credentials/development'
  | Creating buildkite0183e93ce0fd4568be873e083e43031d_deploy-tools-development_run ... done
  | ## Current supported Terraform versions: ['0.13.5', '0.13.7', '0.14.11', '0.15.5', '1.0.0', '1.0.11']
...
```

That last line should've included '1.3.2', which is the newly supported Terraform version in the `latest` deploy-tools image.

We would appreciate any help in solving this.
