### ISSUE TITLE
unsupported option: 'secrets'  error

### ISSUE THREAD

**Issue by murtyk** [buildkite-plugins/docker-compose-buildkite-plugin#367]
Not able to use secrets. This is how docker-compose.ci.yml looks like:

```
secrets:
  aws_access_key_id:
    file: ./amazon_access_key_id.secret
  aws_secret_access_key:
    file: ./amazon_secret_access_key.secret
    
services:
  ci:
    build:
      context: .
      dockerfile: Buildkite.Dockerfile
      args:
        CI: "true"
        SETTINGS_ENV: test
        PRIVATE_SSH_KEY: ${PRIVATE_SSH_KEY}
        NPM_TOKEN: ${NPM_TOKEN}
      secrets:
        - aws_access_key_id
        - aws_secret_access_key 
```

Tried the following syntax also but same error

```
services:
  ci:
    build:
      context: .
      dockerfile: Buildkite.Dockerfile
      args:
        CI: "true"
        SETTINGS_ENV: test
        PRIVATE_SSH_KEY: ${PRIVATE_SSH_KEY}
        NPM_TOKEN: ${NPM_TOKEN}
      secrets:
        - 'id=aws_access_key_id,file=./amazon_access_key_id.secret'
        - 'id=aws_secret_access_key,file=./amazon_secret_access_key.secret'
```
