### ISSUE TITLE
Unable to pass environment variables for interpolation

### ISSUE THREAD

**Issue by suzaku** [buildkite-plugins/docker-compose-buildkite-plugin#379]
I've tried setting `env` in both `step` level and `plugin` level with no luck:

```
env:
- MY_VAR=${MY_VAR}
```

I have also tried setting `propagate-environment: true` for the plugin.

But I get warnings like `The MY_VAR variable is not set. Defaulting to a blank string.` every time.

The version I use is v4.7.0.

**Comment by toote** [comment]
hi @suzaku, I'm not sure I understand what the exact issue is. As far as I understand, the two ways you mentioned should work so I'm quite puzzled.

I have tried these two pipelines and they both work as expected:

```
env:
  MY_VAR: value1
steps:
  - label: test1
    env:
      MY_VAR_2: value2
    command: 'echo $${MY_VAR} and $${MY_VAR_2}'
    plugins:
      - docker-compose#v4.7.0:
          env: [ MY_VAR, MY_VAR_2 ]
          run: tests
```

As well as propagate environment:
```
env:
  MY_VAR: value1
steps:
  - label: test1
    env:
      MY_VAR_2: value2
    command: 'echo $${MY_VAR} and $${MY_VAR_2}'
    plugins:
      - docker-compose#v4.7.0:
          propagate-environment: true
          run: tests
```

The one thing I can say is that your environment definition appears to be wrong (as it is supposed to be a dictionary/map, not a list)
