### ISSUE TITLE
By default build will also push the image to remote repository

### ISSUE THREAD

**Issue by jamesone** [buildkite-plugins/docker-compose-buildkite-plugin#380]
Is this meant to be the default behaviour? I expect it only to push if I define the `push` configuration?

Here is my config:

```yaml
- docker-compose#v4.11.0:
          mount-buildkite-agent: true
          image-repository: REMOTE_REPO
          image-name: base_image_branch-${FRIENDLY_BRANCH_NAME}
          build: base_image
          args:
            - NPM_TOKEN
          environment:
            - FRIENDLY_BRANCH_NAME
          cli-version: 2.2
          cache-from:
            - base_image: REMOTE_REPO:base_image_branch-${FRIENDLY_BRANCH_NAME}
          propagate-environment: true
          config:
            - docker-compose.yml
```

After building successfully, it goes ahead and pushes.
```
:docker: Pushing built images to REMOTE_REPO
```

I would expect it only to push if the push array is present, unless I'm missing something? 

I looked at this merged PR: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/224/files - and the code suggests that it will only push, if the push array present. Main branch still contains this same logic
