### ISSUE TITLE
Use of `env` in step is ignored by docker-compose plugin environment interpolation in commands, resorting to global `env`

### ISSUE THREAD

**Issue by mattmm1** [buildkite-plugins/docker-compose-buildkite-plugin#385]
Hi
I expect that in-step use of `env` variable will be interpreted in docker-compose keys rather than only intrepreting global `env` variables.

I can't tell if this is due to something in buildkite or docker-compose but I have a setup similar to the following:
```
env:
  ENVIRONMENT: dev
  IMAGE_REPO_URL: globalrepo
  BUILDKIT_INLINE_CACHE: 1
    - label: "Build and push containers: Build and push to DEV"
      plugins:
      - ecr#v2.5.0:
          login: true
      - docker-compose#v4.9.0:
          build: myproject-${ENVIRONMENT}
          image-repository: ${IMAGE_REPO_URL}/myproject-${ENVIRONMENT}
          image-name: latest
    - label: "Build and push containers: Build and push to UAT"
      env:
        ENVIRONMENT: uat
        IMAGE_REPO_URL: anotherrepo
      plugins:
      - ecr#v2.5.0:
          login: true
      - docker-compose#v4.9.0:
          build: myproject-${ENVIRONMENT}
          image-repository: ${IMAGE_REPO_URL}/myproject-${ENVIRONMENT}
          image-name: latest
```

I notice that the in step use of `env` is ignored. Both steps use the global `env` settings. Have I used this instep `env` incorrectly or no buildkite plugin supports the use of instep `env` in this way? Or is it an enhancement that could be added to docker-compose plugin?

I'm using `docker-compose#v4.9.0` as in the above example.

Thanks - (love the plugin - constantly using it).
