### ISSUE TITLE
Environment variable interpolation does not work as expected

### ISSUE THREAD

**Issue by dalberto** [buildkite-plugins/docker-compose-buildkite-plugin#39]
Given the following pipeline:

```
env:
  ECR_REPO: "my_ecr_repo.dkr.ecr.us-east-1.amazonaws.com/repo"

steps:
  - name: ":docker: build web"
    agents:
      queue: builders
    plugins:
      docker-compose-buildkite-plugin#v1.1:
        build: web
        config:
          - docker-compose.yml
          - docker-compose.ci.yml
        image-repository: "${ECR_REPO}"
```

When this runs, the `BUILDKITE_PLUGINS` environment variable does not include an `image-repository` key for the plugin.

Instead, I'm forced to add the literal to the config, like so:
```
steps:
  - name: ":docker: build web"
    agents:
      queue: builders
    plugins:
      docker-compose-buildkite-plugin#v1.1:
        build: web
        config:
          - docker-compose.yml
          - docker-compose.ci.yml
        image-repository: "my_ecr_repo.dkr.ecr.us-east-1.amazonaws.com/repo"
```

This is non-ideal because `ECR_REPO` is referenced in multiple subsequent steps throughout the pipeline. Is there a way to avoid the repetition with environment variables, or am I misunderstanding how the environment variable interpolation works?

A slightly different issue occurs when attempting to use the commit as the `image-name`. Given the following configuration:

```
steps:
  - name: ":docker: build web"
    agents:
      queue: builders
    plugins:
      docker-compose-buildkite-plugin#v1.1:
        build: web
        config:
          - docker-compose.yml
          - docker-compose.ci.yml
        image-repository: "my_ecr_repo.dkr.ecr.us-east-1.amazonaws.com/repo"
	image-name: "${BUILDKITE_COMMIT}"
```

The image that is pushed has a tag of `HEAD`. It appears that at the time of pushing, `HEAD` has not been resolved to an actual hash. However, under the `environment` tab, `BUILDKITE_COMMIT` *does* show up as a hash. If I trigger a build with a specific commit, the issue does not occur.

**Comment by lox** [comment]
Thanks for the detailed issue report @dalberto. Looks like there are two different issues here, for the first one:

The top-level `env` block will provide env variables to all steps in your file, but it doesn't make those values available for variable interpolation in the actual pipeline.yml. Variable interpolation is for ENV variables that are already set. What you could do is set `BUILDKITE_PLUGIN_DOCKER_COMPOSE_IMAGE_REPOSITORY` as a top-level env, and then omit the `image-repository` config entirely. I believe this will have the effect you are after.

For the second issue, I'll defer to @toolmantim.

**Comment by dalberto** [comment]
@lox Thanks for the insight. Regarding the first issue, any tips on using the plugin for multiple images in a single pipeline? My real pipeline actually has 3 image builds (e.g. frontend, backend, etc). I suppose I can build multiple pipelines, but I'm wondering if there are easier alternatives, especially because at deploy-time there are dependencies amongst the 3 images (so it's easier to think about it as a single pipeline).

**Comment by lox** [comment]
Do you mean how would you vary the image repository for different steps based on a common repository prefix?

**Comment by dalberto** [comment]
I mean, I actually have 3 completely different ECR repos and I'm trying to build the 3 images in one pipeline, like so:


```
steps:
  - name: ":docker: build web"
    agents:
      queue: builders
    plugins:
      docker-compose-buildkite-plugin:
        build: web
        config:
          - docker-compose.yml
          - docker-compose.ci.yml
        image-repository: my_ecr.dkr.ecr.us-east-1.amazonaws.com/REPO_A
        image-name: "${BUILDKITE_COMMIT}"

  - name: ":docker: build client"
    agents:
      queue: builders
    plugins:
      docker-compose-buildkite-plugin:
        build: client
        config:
          - docker-compose.yml
          - docker-compose.ci.yml
        image-repository: my_ecr.dkr.ecr.us-east-1.amazonaws.com/REPO_B

  - name: ":docker: build nginx"
    agents:
      queue: builders
    plugins:
      docker-compose-buildkite-plugin:
        build: nginx
        config:
          - docker-compose.yml
          - docker-compose.ci.yml
        image-repository: my_ecr.dkr.ecr.us-east-1.amazonaws.com/REPO_C

  - wait
```

As I understand it, setting up a single `BUILDKITE_PLUGIN_DOCKER_COMPOSE_IMAGE_REPOSITORY` env var wouldn't work with this pipeline.

**Comment by lox** [comment]
Ah yup, right. You could pass in an env of `ECR_REPO=my_ecr.dkr.ecr.us-east-1.amazonaws.com` to your builder step and then use variable interpolation like in your first example.

**Comment by dalberto** [comment]
@lox sorry, I don't completely follow. Where should I set `ECR_REPO`?

**Comment by toolmantim** [comment]
@dalberto I think @lox means in your `buildkite-agent pipeline upload` step defined in the Buildkite web UI, in the environment variables section, you could set `ECR_REPO=my_ecr.dkr.ecr.us-east-1.amazonaws.com`. Then in your pipeline YAML you'll be able to do this:

```yml
steps:
  - name: ":docker: build web"
    agents:
      queue: builders
    plugins:
      docker-compose-buildkite-plugin:
        build: web
        config:
          - docker-compose.yml
          - docker-compose.ci.yml
        image-repository: "${ECR_REPO}/REPO_A"
        image-name: "${BUILDKITE_COMMIT}"
```

As for not being able to use `BUILDKITE_COMMIT` in your pipeline.yml file for `HEAD` builds, that should be considered a bug I think. I just filed buildkite/agent#456 for you. Some workaround ideas in the meantime:

* Make sure the `buildkite-agent pipeline upload` command isn't the first step in the pipeline. For example, you could add a `echo 'Finding out commit'` and a `wait` before the pipeline upload
* Calculate the git commit yourself?
