### ISSUE TITLE
Bad tag separator strikes again

### ISSUE THREAD

**Issue by toothbrush** [buildkite-plugins/docker-compose-buildkite-plugin#410]
I just got bitten by what looks like the same issue as https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/352 which led me to https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/353.

This is my pipeline:

```yaml
steps:
  - name: ":docker: Build"
    plugins:
      - docker-compose#v4.14.0:
          # cli-version: 2 # Broken unless i set cli-version: 2
          push:
            - app:myorg/${BUILDKITE_PIPELINE_SLUG}:${BUILDKITE_BUILD_NUMBER}
```

Here's what happens:

```
~~~ Running plugin docker-compose command hook
[90m$[0m /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin-v4-14-0/hooks/command
[90m$[0m docker-compose -f docker-compose.yml -p buildkite018b4b17238a4a8a95d3497da7cdfedf config
~~~ :docker: Building app
[90m$[0m docker-compose -f docker-compose.yml -p buildkite018b4b17238a4a8a95d3497da7cdfedf build app
#1 [app internal] load build definition from Dockerfile
#1 transferring dockerfile: 109B done
#1 DONE 0.0s

[... bunch of building...]

#6 [app] exporting to image
#6 exporting layers done
#6 writing image sha256:9fab1a6b4f3fb7ca52968d91c762fc55fa84aa9191a7ebf10547772f06d5de58 done
#6 naming to docker.io/library/buildkite018b4b17238a4a8a95d3497da7cdfedf-app done
#6 DONE 0.0s

~~~ :docker: Pushing image myorg/app-template
[90m$[0m docker tag buildkite018b4b17238a4a8a95d3497da7cdfedf_app myorg/app-template
Error response from daemon: No such image: buildkite018b4b17238a4a8a95d3497da7cdfedf_app:latest
```

The eagle-eyed reader will see a problem: `...97da7cdfedf-app` versus `...97da7cdfedf_app` as the image name.

I haven't found where this default is coming from (i'll investigate and update the issue), but it seems our Buildkite agents are defaulting to CLI version 2 whereas the plugin is assuming we're on v1. However, specifying `cli-version: 2` fixed the issue.  I'm wondering if i should try and cook up a PR that either robustly works out which CLI version we're using, or working out the name of the image we just built.
