### ISSUE TITLE
Docker compose: 5.2.0  - unknown shorthand flag: 'f' in -f 

### ISSUE THREAD

**Issue by moribaleta** [buildkite-plugins/docker-compose-buildkite-plugin#439]
Hi Guys Im trying to use 5.2.0 coming from 3.9.0
I'm getting this error on buildkite
```

Building services build-${BUILDKITE_BRANCH}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT} | 0s
-- | --
  | $ docker compose -f docker-compose.yml -p buildkite018f75692ece423b91a4b2fc60fba6c6 build --pull build-${BUILDKITE_BRANCH}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}
  | unknown shorthand flag: 'f' in -f


```
any thoughts on whats causing the issue

this is my step in pipeline.yml
```
steps:
  - label: ":docker: Build image on host"
    branches: "development staging alpha beta gamma master"
    plugins:
      - ecr#v2.9.0:
          login: true
          region: "us-east-1"
          no-include-email: true
      - docker-compose#v5.2.0:
          build: "build-${BUILDKITE_BRANCH}-${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}"
          push: ****
          config: docker-compose.yml
          env:
            - BUILDKITE_BRANCH
```
