### ISSUE TITLE
Ability prepare step before run docker-comopse

### ISSUE THREAD

**Issue by velios** [buildkite-plugins/docker-compose-buildkite-plugin#440]
Hi. First of all, thank you very much for such a wonderful plugin.

I have a slight misunderstanding about what needs to be done to perform some settings on the agent before running docker and is this possible? I expected that a command at the step level was created for this, but it passes directly to the docker. Are there any mechanisms for preparing the agent before run docker-compose ?

```
  - label: "Format namespaces"
  plugins:
  - docker-compose#v5.2.0:
      pre-steps: "some preparation command" # is it possible make something like this?
      run: "fmt-ns"
      command: ["check"] # docker-compose run fmt-ns check
      mount-checkout: true
      workdir: "/app"
  retry:
    automatic:
      - exit_status: "*"
        limit: 1
```

I understand it can be done with pre-command hook, but intrested in another options

**Comment by velios** [comment]
Or like in documentation example

```
- plugins:
      - docker-login#v2.0.1:
          username: xyz
      - docker-compose#v5.2.0:
          build: app
          push: app:index.docker.io/myorg/myrepo:tag

```

but instead of docker-login call some custom user command

**Comment by velios** [comment]
Solved, but hacky. By adding my own plugin. 
It seems like it would be nice if the plugin had a pre-command hook that would be controlled by a separate argument. For preparation steps. Supports both passing strings and vectors of strings.

```
  label: "Format namespaces"
  plugins:
  - velios/hooks#v1.0.0:
      precommand: "some-command-line-tool container registry configure-docker"
  - docker-compose#v5.2.0:
      run: "fmt-ns"
      command: ["check"] # check - режим не меняющий файлы внутри volume
      mount-checkout: true
      workdir: "/app"
  retry:
    automatic:
      - exit_status: "*"
        limit: 1
```

If this feature is not desirable, then the task can be closed; I have described a workaround.
