### ISSUE TITLE
Proposal: script directive for executing a script rather than calling run/build

### ISSUE THREAD

**Issue by lox** [buildkite-plugins/docker-compose-buildkite-plugin#47]
I find myself often writing scripts for calling docker-compose that pull the image from a previous build step. I'd love a way to automate some of the boiler plate of those. This is an example:

```bash
#!/bin/bash
set -eu

cleanup() {
  docker-compose kill || true
  docker-compose rm --force -v || true
  docker-compose down -v || true
}

trap cleanup EXIT

image_name=$(buildkite-agent meta-data get docker-compose-plugin-built-image-tag-blah)

export COMPOSE_PROJECT_NAME="buildkite$$" 
docker pull "$image_name"

... do docker-compose stuff
```

What if this could be:

```
steps:
  - command: test.sh
    plugins:
      docker-compose:
        script: my_custom_compose_script.sh
```

and the script could just be the docker-compose bits? Possibly even with a `docker-compose-with-config` function that calls the config files from the config.

Would save much pain, and allows extending on the plugin functionality without losing all of the nice bits.

**Comment by toolmantim** [comment]
I wonder if it should be called `command`?

And sourced, so it has access to the functions? That will make the functions a public API then, which is not necessarily a problem but we probably want to be clear if there are any that we don't want people to depend upon.

**Comment by lox** [comment]
Possibly, I guess that `command` sounds a lot like Docker's `CMD`. 

I reckon if we did this we'd really limit what was exposed to the script, but yeah, it would be sourced I think.

**Comment by lox** [comment]
This has come up again, would be a nice way of calling custom run params that haven't been implemented yet. How about `run-script`, which would be a script called instead of the docker-compose run command. It would specifically override this line https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/3c1e578c636f7493cf65ac0c2302ec3eef6594e8/commands/run.sh#L141

```
  - command: test.sh
    plugins:
      docker-compose:
        run-script: my_custom_compose_script.sh
```

Then `my_custom_compose_script.sh` would look something like:

```bash
#!/bin/bash
set -euo pipefail

docker-compose -f docker-compose.yml -f "$BUILDKITE_DOCKER_COMPOSE_OVERRIDE" run --rm myservice
```

It would get invoked in a subshell with a specific set of ENV that it was passed from the parent plugin script, e.g `BUILDKITE_DOCKER_COMPOSE_OVERRIDE` with the override file generated. 

It would be super "advanced users only", but would be a great way of customizing behaviour.

**Comment by toolmantim** [comment]
I haven’t checked, but I think you might still need the service name to ensure all the other bits work properly? Something like:

```yml
  - command: test.sh
    plugins:
      docker-compose:
        run: service
        command-override: my_custom_script.sh
```

This also means you can document it as a “run command only” options like the rest of them, rather than introducing another top-level key.
