### ISSUE TITLE
Error when pushing tag built from branch with a `/` in it

### ISSUE THREAD

**Issue by jonleighton** [buildkite-plugins/docker-compose-buildkite-plugin#479]
We have some `build` configuration that looks like this:

``` yaml
        push:
          - app:registry/path:app-${BUILDKITE_BRANCH}
```

This works fine usually, but when `BUILDKITE_BRANCH` contains a `/` (or presumably other characters too, but that's the problematic one for us), we get the following error during the push:

```
Error parsing reference: "registry/path:app-the/branch" is not a valid repository/tag: invalid reference format
```

The `/` needs to be escaped or filtered somehow. We are doing this ourselves for now, but it would be great if this plugin could handle it better.

(This worked fine for us prior to upgrading the v5, so it seems to be a regression, actually.)

**Comment by bjeanes** [comment]
I would add that, at least so far, we have not found a straight-forward way provide a "sanitised" branch name here. We've had to introduce some indirection in our pipeline by preprocessing the pipeline definition before uploading it.

If there is a way to produce a clean value in one step to pass it to a subsequent step that can be used in plugin configuration (vs in a command, which could use the BK CLI to pull down metadata) we haven't found it, which makes this pretty burdensome complexity in the pipelines of all of our repositories that want to use v5 of this plugin.

**Comment by toote** [comment]
@bjeanes that is indeed really weird! I have been reviewing the [code paths of v4.16.0](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/tree/v4.16.0) and have yet to figure out how a branch name with a `/` would result in a valid configuration for pushing as the [`image-name` parameter was used as-is after the `image-repository`](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/v4.16.0/commands/build.sh#L110-L121) which would now translate to `service:IMAGE_REPOSITORY:IMAGE_NAME`.

Would you be able to provide a configuration example for that version so that I can further review it?

The only alternative that I can think of would be to have a special variable like `SANITIZED_BRANCH` name and change your default step in the pipeline to define that value before doing the `buildkite-agent pipeline upload`. For example:

```
export SANITIZED_BRANCH="$(echo -n "${BUILDKITE_BRANCH" | tr -cs 'A-Za-z0-9_' '_')"
buildkite-agent pipeline upload .buildkite/pipeline.yml # this file uses $SANITIZED_BRANCH instead of $BUILDKITE_BRANCH
```

**Comment by bjeanes** [comment]
> Would you be able to provide a configuration example for that version so that I can further review it?

The relevant section before upgrading to v5 was more-or-less:

```yaml
steps:

  - name: ":docker: CI images"
    plugins:
      docker-compose#v4.14.0:
		buildkit: true
		config: docker-compose.ci.yml
		propagate-environment: true
		tty: false
		upload-container-logs: always
		env:
		  - BUILDKITE_AGENT_ACCESS_TOKEN
        build-parallel: false
        build: app
        build-alias:
          - app-es
        image-repository: registry:5000/manuka/ci
        separator-cache-from: "|"
        cache-from:
          - app|registry:5000/manuka/ci|app-${BUILDKITE_BRANCH}
          - app|registry:5000/manuka/ci|app-main
        push:
          - app:registry:5000/manuka/ci:app-${BUILDKITE_BRANCH}
          - app:registry:5000/manuka/ci:app-${BUILDKITE_COMMIT}
```

It is conceivable that the `/` was being dropped in some way before and that we were actually just pushing and pulling the prefix with a silent failure and now we get a hard error?

> The only alternative that I can think of would be to have a special variable like `SANITIZED_BRANCH` name and change your default step in the pipeline to define that value before doing the `buildkite-agent pipeline upload`. For example:

This is more or less what we are doing now, yup.

**Comment by toote** [comment]
@bjeanes thanks a lot for the information! I checked out version 4.16.0 and tested a variation of your configuration:

```yaml
  push: myservice:my.repository/myservice:testing/llamas
  build: myservice
  iamge-repository: my.repository/myservice
```

And the output showed that several things happened:
* the lack of `image-name` means it creates a default tag using the pipeline name and build id

```
~~~ :docker: Creating a modified docker-compose config
  version: '2'
  services:
    myservice:
      image: my.repository/myservice:test-myservice-build-1
+++ :docker: Building services myservice
$ docker-compose -f docker-compose.yml -p buildkite1111 -f docker-compose.buildkite-1-override.yml build --pull myservice built myservice
~~~ :docker: Pushing built images to my.repository/myservice
$ docker-compose -f docker-compose.yml -p buildkite1111 -f docker-compose.buildkite-1-override.yml push myservice pushed myservice

$ buildkite-agent meta-data set docker-compose-plugin-built-image-tag-myservice my.repository/myservice:test-myservice-build-1
set metadata docker-compose-plugin-built-image-tag-myservice to my.repository/myservice:test-myservice-build-1

$ docker-compose -f docker-compose.yml -p buildkite1111 config
🚨 specified image to push myservice:my.repository/myservice:testing/llamas has an invalid tag so it will be ignored
```

So it was indeed a silent failure
