### ISSUE TITLE
`require-prebuild` doesn't work if some but not all images are prebuilt

### ISSUE THREAD

**Issue by jonleighton** [buildkite-plugins/docker-compose-buildkite-plugin#483]
We have a configuration where a step requires multiple images to run. The images are build in a previous `build` step. However, we had accidentally not specified one of the images in the `push` key. The config looked something like this:

``` yaml
steps:
    - name: build
      plugins:
        docker-compose#v5.7.0:
          build:
            - a
            - b
          push:
            - a

    - command: run-the-thing
      plugins:
        docker-compose#v5.7.0:
          run: b
          require-prebuild: true
          pull:
            - a
            - b
```

In this case, an override for `b` was missing during the "Creating docker-compose override file for prebuilt services" part.

The `docker compose pull` of `b` failed silently like so:

```
 ✔ a Pulled                             0.0s 
 ✔ b Skipped - No image to be pulled 0.0s 
```

The `docker compose up` part ("Starting dependencies") ended up automatically building `b`.

I would expect the `require-prebuild: true` option to cause the step to fail in this situation. However, it looks like the logic only checks for the existence of the override file:

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/69b94f6c19ed5ca96f2082be171d8728b76b9a95/commands/run.sh#L353-L360

In our case, the override file existed, but didn't specify an image for `b` due to the missing entry under `push`.
