### ISSUE TITLE
Add support for multiple commands?

### ISSUE THREAD

**Issue by joshma** [buildkite-plugins/docker-compose-buildkite-plugin#59]
It looks like multiple commands aren't supported:
```
steps:
  - label: ':hammer: Test'
    command:
      - 'echo COMMAND_1'
      - 'echo COMMAND_2'
    plugins:
      docker-compose:
        run: tests
        config: docker-compose.buildkite.yml
```

I see that it tries to run: `docker-compose -f docker-compose.buildkite.yml -p buildkite82973f2986fe406c9a67a03338bca53e run tests echo COMMAND_1 echo COMMAND_2`

And my guess is that https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/hooks/commands/run.sh#L43 passes in $BUILDKITE_COMMAND as an array.

Would it be possible to have that line in `run.sh` iterate over each item of `$BUILDKITE_COMMAND` and run then sequentially?

As a workaround, I'm including the repeated step inside the first command (a shell script), but it'd be nice to specify multiple command to re-use e.g. a script that processes xunit.xml output files.

**Comment by lox** [comment]
Probably the more docker-compose like alternative would be to translate it to a single command using `/bin/sh` or `/bin/bash`:

```yaml
steps:
  - label: ':hammer: Test'
    command: >
      bash -c "echo COMMAND_1 &&
                     echo COMMAND_2"
    plugins:
      docker-compose:
        run: tests
        config: docker-compose.buildkite.yml
``` 

Do you specifically want to run it multiple times in different containers? I'd be interested hearing more about the specific usecase if you can share.

**Comment by joshma** [comment]
Hrm that's fair, I'll go the bash route, thanks!

In my case, I have a command that runs tests and generates XML files for unit test results and coverage results. I'm re-using that test in a pipeline for phabricator, and in that pipeline I want to add a follow-up command to upload this data to phabricator. So it's only a slight difference for me to use `bash -c "cmd_1 && cmd_2"`.

I was mostly hoping for multiple `command` to work since it's consistent with running it outside of the docker-compose plugin, and it might be confusing to others setting things up that this isn't the way to do it. Feel free to close if you don't think it's worth fixing, just my 2c.

**Comment by lox** [comment]
Yup, I hear ya. Torn between the expectations that docker-compose brings and buildkite-agent does :) 

Let's leave this open and see what other people think. Thanks for raising the issue!

**Comment by thomasbarton** [comment]
@lox It would be nice if buildkite automatically translated multiple commands into the bash format.  I am running into the issue of having 2 commands.  The first being a wait_for_it.sh script that allows me to wait for a mysql container to start.

**Comment by dominics** [comment]
This limitation (which is _completely_ understandable) should probably be documented in the README - even though nothing in the README gives the impression that multiple commands would be supported, it'd have saved me a bit of debugging.

**Comment by lox** [comment]
I think we've settled on making `/bin/bash -c` the default "shell" and letting folks customize this with a `shell` directive.

**Comment by dominics** [comment]
@lox On further testing, I can't actually get the `bash -c` workaround to work, because of escaping applied to the run command. For example, using a command like:

```yaml
  - label: "single quotes, folded"
    command: >
      sh -c 'echo foo && echo bar'
    plugins:
      docker-compose#v1.8.2:
        run: some-container
```

Results in a run line like

```
docker-compose -f docker-compose.yml [...] run some-container sh -c \'echo foo \&\& echo bar\'
```

Which is a `foo: line 1: syntax error: unterminated quoted string`. Same goes for all combinations of double and single quotes I've tried (including using a simple YAML string as opposed to a folded one). I just can't get the plugin to leave my command alone and pass it as-is into the run line.

(The obvious workaround in the meantime is to shove the two commands into a script, of course)
