### ISSUE TITLE
Support parallel build steps in pipeline

### ISSUE THREAD

**Issue by KevinGrandon** [buildkite-plugins/docker-compose-buildkite-plugin#60]
We would like to build multiple services through docker-compose across machines to parallelize build time.

Given a pipeline like the following we would expect service 1 and service 2 to be built in parallel. I believe today we can build them, but for some reason further steps will be unable to download the first service and they will be built locally.

```
- name: "SERVICE 1"
  plugins:
    docker-compose:
      build: service1
      image-repository: <repo>
      config: service1/docker-compose.yml
- name: "SERVICE 2"
  plugins:
    docker-compose:
      build: service2
      image-repository: <repo>
      config: service2/docker-compose.yml
- wait
- name: "1st service script"
  command: "ci/script"
  plugins:
    docker-compose:
      run: service1
      config: webapp/docker-compose.yml
- name: "2nd service script"
  command: "ci/script"
  plugins:
    docker-compose:
      run: service2
      config: service2/docker-compose.yml
```
