### ISSUE TITLE
Using commands with this plugin doesn't appear to work

### ISSUE THREAD

**Issue by hartror** [buildkite-plugins/docker-compose-buildkite-plugin#75]
Using this plugin and this step:

```
  - label: build
    commands:
      - python setup.py sdist
      - buildkite-agent artifact upload dist/*.tar.gz
    plugins:
      docker-compose#v1.5.2:
        run: app
        config: docker-compose.buildkite.yml
```

I expected either two calls to docker-compose or a single call using bash eg:

`docker-compose -f docker-compose.buildkite.yml run app bash -c "python setup.py sdist && buildkite-agent artifact upload dist/*.tar.gz"`

Instead the command reported by buildkite is:

`docker-compose -f docker-compose.buildkite.yml -p buildkited85f2a76afb84b34ba66557c6bd4dc25 run app python setup.py sdist buildkite-agent artifact upload dist/\*.tar.gz`

Where the commands are concatenated without any handling.

**Comment by hartror** [comment]
Not sure if this is related by trying this also fails:

```
  - label: build
    command: bash -c 'python setup.py sdist && buildkite-agent artifact upload dist/*.tar.gz'
    plugins:
      docker-compose#v1.5.2:
        run: app
        config: docker-compose.buildkite.yml
```

Being translated into: 

`docker-compose -f docker-compose.buildkite.yml -p buildkitee2e0d5575b724c4585398c27d4128b87 run app bash -c \'python setup.py sdist \&\& buildkite-agent artifact upload dist/\*.tar.gz\'`
