### ISSUE TITLE
Dowload artifacts support

### ISSUE THREAD

**Issue by mazzy89** [buildkite-plugins/docker-compose-buildkite-plugin#79]
It is not possible to download artifacts when we use this plugin. Consider to add an option to pull down artifacts

**Comment by lox** [comment]
I created https://github.com/buildkite-plugins/artifacts-buildkite-plugin to help with this!

**Comment by grrowl** [comment]
@lox `artifacts-buildkite-plugin` works great! There is an issue when combining it with `docker-compose-buildkite-plugin`, though:

```yaml
steps:
  - name: "compile assets"
    plugins:
      - docker-compose#v3.0.3:
        run: node
        command: ["webpack"]
        volumes:
          - "./tmp/webpack:/app/public/assets/webpack"
      - artifacts#v1.2.0:
        upload: "tmp/webpack/**/*"

  - wait

  - name: "build app image"
    plugins:
      - artifacts#v1.2.0:
        download: "tmp/webpack/*"
      - docker-compose#v3.0.3:
        build:
          - app
```

The build logs illustrate the problem: since `docker-compose` is run in its own `/var/lib/docker/tmp` directory, it can't access (or at least isn't aware of the location of) the downloaded artifacts in the `/var/lib/buildkite-agent/` directory

```
# Download artifacts
Searching for artifacts: "tmp/webpack/*"
Found 21 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/buildkite-builders-i-00736d6e0c0fbcf65-2/organisation/project
```
```
# Building service app
Service 'app' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder244640397/tmp/artifacts/webpack
```

---

I've tried passing a build arg with the artifact path like so, but Dockerfile doesn't like absolute paths:

```yaml
        args:
          - WEBPACK_ASSETS=/var/lib/buildkite-agent/builds/${BUILDKITE_AGENT_NAME}/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/tmp/webpack
```
```dockerfile
ARG WEBPACK_ASSETS
COPY ${WEBPACK_ASSETS} ./public/assets/webpack/
```
```
# Building service app
Service 'app' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder250188356/var/lib/buildkite-agent/builds/buildkite-builders-i-00736d6e0c0fbcf65-2/organisation/project/tmp/webpack: no such file or directory
```

So I wonder — is there any way to make artifacts available to `buildkite-plugin-docker-compose` build steps?
