### ISSUE TITLE
BUILDKITE_PLUGIN_DOCKER_COMPOSE_BUILD is empty

### ISSUE THREAD

**Issue by andrba** [buildkite-plugins/docker-compose-buildkite-plugin#84]
The docs say that `image-name` default value is built using `BUILDKITE_PLUGIN_DOCKER_COMPOSE_BUILD` variable:
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/#image-name-optional.

Looks like this variable is gone now. Is there a way to get a current service name in `image-name` when building multiple services in one step?

**Comment by lox** [comment]
I'd guess that we broke this when we added support for multiple build items, as the relevant vars would be `BUILDKITE_PLUGIN_DOCKER_COMPOSE_BUILD_0`, `BUILDKITE_PLUGIN_DOCKER_COMPOSE_BUILD_1`, etc. You should be able to use those!

**Comment by shaneog** [comment]
> You should be able to use those!
How can I use these?
Does `image-name` accept an array?

I'm trying to build multiple images and my build step looks like this:

```yaml
  - name: ":docker: Build"
    agents:
      queue: docker-builder
    plugins:
      docker-compose#v1.8.2:
        build:
          - app
          - release
        config:
          - docker-compose.ci.yml
        image-name: ${BUILDKITE_PLUGIN_DOCKER_COMPOSE_BUILD}-${BUILDKITE_COMMIT:0:7}
```
