### ISSUE TITLE
Option for outputting service logs during execution

### ISSUE THREAD

**Issue by KevinGrandon** [buildkite-plugins/docker-compose-buildkite-plugin#98]
**The problem:**
Services which are spun up with `depends_on` will not display log output during execution. 

We have a docker-compose service list as follows:
```yaml
version: '2.1'
services:
  my-server:
    build: .
    command: yarn start
    expose:
      - 8080
    ports:
      - "8080:8080"
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "curl -H \"Accept: text/html\" -f http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  server-healthy:
    build: .
    network_mode: "host"
    depends_on:
      my-server:
        condition: service_healthy

  run-service:
    build: .
    network_mode: "host"
    depends_on:
      - server-healthy
    command: ./test.sh
```

It seems that this is either not documented, or it's not supported, but right now it seems impossible to get the log output of `my-server` with this plugin.  (Docker-compose eats depends_on service log output by default).

**Solution for local development:**
Developers can manually view output in another terminal tab, via a command like: `docker-compose logs -f my-service`

**Possible solutions for this plugin:**

* One possible solution would be a new configuration option allowing developers to tail docker-compose output of selected services. An example of the pipeline implementation:

```yaml
  - name: 'run tests'
    command: ./test.sh
    plugins:
      'docker-compose#v1.8.0':
        run: run-service
        logs:
          - my-server
          - my-other-service
```

* It might also be nice if we could have multiple UI tabs for output of different services in the Buildkite frontend, but that would likely require changes in the frontend product, and is not nearly as important as being able to see the logs in the first place.
* If we can't have background tabs during execution, perhaps running `docker-compose logs -f <services> &` before the docker-compose run script would be sufficient.
